layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.6350217
  lightness: 0.8914894
  rhythmicContrast: 0
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 1
name: JLAW
