name: JLAW
favicon: null
layout_spectrum: 0.52475
typography_spectrum: 0.53218
title: (BETA)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#052a01'
    - '#094601'
    - '#028500'
    - '#066c01'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
